### ISSUE TITLE
Move to list

### ISSUE THREAD

**Issue by nicobar** [nicobar/NX36-L#12]
https://github.com/nicobar/NX36-L/blob/e703397c76ad0240b34abb67b1ce7402a0de45af/NX36-L/Sites/PA01_sample/site_config_PAOSW011-2.json#L16

This has to be a list with elem = prefix/lenght
E.G:
!
ip access-list MGW_OM
 10 permit ip 10.193.95.128/27  ! VLAN187 VEMGW04_Lan_O&M
 20 permit ip 10.193.91.160/27  ! VLAN297 VEMGW03_Lan_O&M
 1000 deny ip any any
!

**Comment by GaetanoCarlucci** [comment]
done
