### ISSUE TITLE
Name of Variables

### ISSUE THREAD

**Issue by nicobar** [nicobar/NX36-L#4]
https://github.com/nicobar/NX36-L/blob/70f7ef665facff053f80c26c1bd7ba9028915bef/NX36-L/Sites/PA01/site_config_PAOSW011.json#L2

Let's find a smart way to rename variables, considering sx and dx NE chains

**Comment by GaetanoCarlucci** [comment]
I will work on that!

**Comment by nicobar** [comment]
Moreover we have to add for stage 2 (better to add a comment in json to explicit variable meaning/where used 
FREE_TEMP_OPT = 0
FREE_TEMP_COPPER = 0
FREE_TEMP_TE = 0
